version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: high-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      - DJANGO_SETTINGS_MODULE=high_api.settings
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    env_file:
      - .env

  postgres:
    image: postgres:13
    container_name: high-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
